### ISSUE TITLE
Is there is a way to specify the trial_duration in flips (for a rapid presentation without responses on every presentation)?

### ISSUE THREAD

**Issue by sophia-shatek** [kurokida/jspsych-psychophysics#25]
Hello, thank you so much for this plugin, it's been amazingly helpful! The examples are very useful. 

I am running an experiment where participants view a series of rapidly presented images (RSVP), displayed for 200ms each. They only need to respond when they see a target. I can specify the duration of each image in frames using the 'is_frame' and 'show_end_frame' parameters of the image, but to have the trial end without accepting a response (set 'response_ends_trial' = false) the 'trial_duration' parameter needs a value in milliseconds. This means that the timing is misaligned when the frames don't line up with the millisecond specification and it is not ideal. I have tried only using the 'trial_duration' parameter, but this also leads to inconsistent timing. I am a beginner in javascript, so it's very possible that I'm just missing something or using the wrong combination of variables. 

Is there a way to specify the trial_duration in flips in the plugin? Or if not, is there another way to show multiple stimuli rapidly without requiring a response? 

For example, here's some of my code for displaying a stream of single images in the periphery, with a fixation cross in the centre: 

```javascript
// a single image shown either side of fixation
    single_presentation = {
      obj_type: 'image',
      origin_center: true,
      startX: function(){
        if (jsPsych.timelineVariable("presentation_side")=='left'){
          return -300;
        } else {
          return 300;
        }
      },
      startY: 0,
      file: jsPsych.timelineVariable('image'),
      scale: 0.5,
    //is_frame: true, 
    //show_end_frame: 12
    }

    // combine single image with fixation cross 
    single_picture_display = {
      type: 'psychophysics',
      response_ends_trial: false,
      trial_duration: 200,
      stimuli: [single_presentation, fixation],
      data: {"display_item": "stimulus", "display_type": "single"}
    }

    // loop over the trial variables to make a rapid stream of images 
      single_trial = {
        timeline: [single_picture_display, isi],
        timeline_variables: tv
      }
      timeline.push(single_trial)
```

**Comment by kurokida** [comment]
Thank you for using my plugin!

I'm not sure I understand your question exactly, so let me check a few things.

Assume that 10 images are presented in succession for 200 ms each.
In this case, as you mentioned, the is_frame property should be true, the show_end_frame should be 12, and the trial_dration should be 2000.
Does your question imply that the presentation time of the last image will be slightly shorter than ideal (e.g., 10 or 11 frames) ?

If you mind this, why not set the trial_dration property a little longer, say 2100ms? Even if there is a small amount of blank time, it probably won't affect the experiment.

By the way, we should note that the the time for one frame is not necessarily 16.7ms (=1000ms/60Hz).
I suspect that the refresh rate of a display varies from computer to computer.
With that in mind, it may be better to specify in milliseconds rather than frames.

In online experiments, the accuracy is not particularly better when specified in frames than when specified in milliseconds.
See [the histgrams](https://www.hes.kyushu-u.ac.jp/~kurokid/histograms20201217/histogram20201216.html) which was made previously using my plugin.

**Comment by sophia-shatek** [comment]
Thanks for your rapid response! With your clarification, I guess my issue must be from the structure I'm using to set up sequences. 

Because the stimuli need a fixation cross in between (200ms picture/ 100ms fixation/ 200ms picture/ 100ms fixation), I tried to combine these into a single stream, as below. In this case, the 'trial_duration' still refers to a single image/fixation cross presentation? If I set it as a longer time then it just presents a single image and waits for a response. I am not sure how to set the trial duration for the entire stream rather than an individual image presentation as you suggest in your response.

```
var dual_picture_display = {
      timeline:[{type: 'psychophysics',
              response_ends_trial: false,
              trial_duration: 300,
              stimuli: [
                 {//right presentation
                  obj_type: 'image',
                  origin_center: true,
                  startX: 300,
                  startY: 0,
                  file: jsPsych.timelineVariable('im2'),
                  scale: 0.5,
                  show_end_frame:12,
                  is_frame: true,
                },
                 { //left presentation
                  obj_type: 'image',
                  origin_center: true,
                  startX: -300,
                  startY: 0,
                  file: jsPsych.timelineVariable('im1'),
                  scale: 0.5,
                  show_end_frame:12, //200ms
                  is_frame: true
                },
                { //fixation
                  obj_type: 'image',
                  origin_center: true,
                  startX: 0,
                  startY: 0,
                  file: 'fixation.png',
                  scale: 0.02,
                  show_end_frame:18, //300 ms - includes 100ms ISI
                  is_frame: true
                }]}],
      data: {"disp_item": "stimulus", "display_type": "dual" },
      timeline_variables: [{im1: 'stimuli/animate_face_3.png', im2: 'stimuli/inanimate_boats_2.png'},
                                       {im1: 'stimuli/inanimate_tools_4.png', im2: 'stimuli/animate_fish_4.png'},
                                       {im1: 'stimuli/animate_fish_1.png', im2: 'stimuli/inanimate_boats_2.png'},
                                       {im1: 'stimuli/inanimate_boats_2.png', im2: 'stimuli/animate_face_1.png'},
                                       {im1: 'stimuli/animate_fish_3.png', im2: 'stimuli/animate_face_4.png'}
      ]
    }
    timeline.push(dual_picture_display)
```

**Comment by kurokida** [comment]
Hi, @sophia-shatek ,

Your sample code will probably present two images at the same time because the show_start_time is not specified (the default is 0 ms).
Is that what you want to do? Maybe I don't thik so.

If you want to present 10 images in a single trial, you have to specify 10 image objects and specify different  show_start_time and show_end_time for each image.

The trial_duration property means duration for the entire stream not for each image.

Example code:

```javascript

var image1 = {
  obj_type: 'image',
  origin_center: true,
  startX: 300,
  startY: 0,
  file: jsPsych.timelineVariable('im1),
  scale: 0.5,
  show_start_frame: 0,
  show_end_frame:12,
  is_frame: true,
}

var image2 = {
  obj_type: 'image',
  origin_center: true,
  startX: 300,
  startY: 0,
  file: jsPsych.timelineVariable('im2),
  scale: 0.5,
  show_start_frame: 20, // This means ISI = 8 frame
  show_end_frame:32,
  is_frame: true,
}

var image3 = {
  obj_type: 'image',
  origin_center: true,
  startX: 300,
  startY: 0,
  file: jsPsych.timelineVariable('im3),
  scale: 0.5,
  show_start_frame: 40, // This means ISI = 8 frame
  show_end_frame: 52,
  is_frame: true,
}

{
  type: 'psychophysics',
  response_ends_trial: false,
  trial_duration: 3000, // For the entire stream / One trial
  stimuli: [image1, image2, image3]
}

```

The code above works, but it is not sophisticated.
Please see [a better code](https://codepen.io/kurokida/pen/KKqwzyE?editors=0010).

**Comment by sophia-shatek** [comment]
Ah thank you! This makes much more sense - I need to update the 'show_start_frame' and 'show_end_frame' dynamically in a loop. Thank you very very much for the help and the example code. It seems very obvious now that you have pointed it out. I really appreciate the plugin, all the example code, and your responsiveness to help me solve my silly problem!
